# Python 數據分析與挖掘實戰

第1章 基礎數據挖掘

In [2]:
a = 2
a * 2
a ** 2

4

In [7]:
a, b, c = 2, 3, 4 # 超神啊啊啊啊啊
print(a, b, c)
print(a, b)
print(c)

2 3 4
2 3
4


In [9]:
s = 'I like Python'
print(s + ' very much')
s.split(' ')

I like Python very much


['I', 'like', 'Python']

In [12]:
if a == 1: # Python不使用{}和end
    print(a)
else: # Python用縮排代表層次
    print('a不等於1')

a不等於1


In [17]:
s, k = 0
while k < 101:
    k = k + 1
    s = s + k
print(s)

TypeError: 'int' object is not iterable

In [18]:
s = 0
if s in range(4):
    print('s在0, 1, 2, 3中')
if s not in range(1, 4, 1): # 第一個1為首項，第二個1為公差，4代表末項為4-1
    print('s不在1, 2, 3中')

s在0, 1, 2, 3中
s不在1, 2, 3中


In [19]:
def add2(x):
    return x + 2
print(add2(1))

3


In [21]:
def add2(x = 0, y = 0):
    return([x + 2, y + 2]) # 返回列表
def add3(x, y):
    return(x + 3, y + 3) # 雙重返回
a, b = add3(1, 2)
print(a, b)

4 5


In [ ]:
f = lambda x: x + 2 # f(x) = x + 2
g = lambda x, y: x + y # g(x, y) = x + y

In [23]:
a = [1, 2, 3]
b = []
for i in a:
    b.append(i + 2)

# 簡化版
a = [1, 2, 3]
b = [i + 2 for i in a] # 直觀的語法，稱為「列表解析」，本質仍是for指令，而Python的for指令效率不高，用map()較佳

In [26]:
d = {'today': 20, 
     'tomorrow': 30}
d['today']
d['tomorrow']

dict([['today', 20], ['tomorrow', 30]]) # 另種寫法
dict.fromkeys(['today', 'tomorrow'], [20]) # 兩個key都對應到20

{'today': [20], 'tomorrow': [20]}

In [36]:
b = [i + 2 for i in a]

b = map(lambda x: x + 2, a)
b = list(b) # map()用於逐一遍歷，速度相當於C語言
from functools import reduce
reduce(lambda x, y: x * y, range(1, n + 1)) # reduce()用於遞歸計算

s = 1
for i in range(1, n + 1):
    s = s * i # 相當於上式

b = filter(lambda x: x > 5 and x < 8, range(10))
b = list(b)

NameError: name 'n' is not defined

In [37]:
import math
math.sin(1)
math.exp(1)
math.pi

3.141592653589793

In [35]:
from math import exp as e
e(1)
sin(1) # error，sin()沒被導入

NameError: name 'sin' is not defined

In [ ]:
from math import *  # 全部導入容易引起命名衝突
exp(1)
sin(1)

In [39]:
import numpy as np
a = np.array([2, 0, 1, 5])
print(a)
print(a[:3])
print(a.min())
a.sort()
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b * b)

[2 0 1 5]
[2 0 1]
0
[[ 1  4  9]
 [16 25 36]]


In [41]:
from scipy.optimize import fsolve
def f(x):
    x1 = x[0]
    x2 = x[1]
    return[2 * x1 - x2 ** 2 - 1, x1 ** 2 - x2 - 2] # return可以回傳任何類型的東西
result = fsolve(f, [1, 1])
print(result)

from scipy import integrate
def g(x):
    return(1 - x ** 2) ** 0.5
pi_2, err = integrate.quad(g, -1, 1)
print(pi_2 * 2)

[ 1.91963957  1.68501606]
3.1415926535897967


In [46]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 1000)
y = np.sin(x) + 1
z = np.cos(x ** 2) + 1

plt.figure(figsize = (8, 4)) # 設定圖像大小
plt.plot(x, y, label = '$\sin x + 1$', color = 'red', linewidth = 2)
plt.plot(x, z, 'b--', label = '$\cos x ^ 2 + 1 $')
plt.xlabel('Time(s) ')
plt.ylabel('Volt')
plt.title('A Simple Example')
plt.ylim(0, 2.2)
plt.legend()
plt.show()

In [ ]:
import pandas as pd
s = pd.Series([1, 2, 3], index = ['a', 'b', 'c'])
d = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns = ['a', 'b', 'c'])
d2 = pd.DataFrame(s)

d.head()
d.describe()

pd.read_excel('data.xls')
pd.read_csv('data.csv', encoding = 'utf-8')

In [47]:
from statsmodels.tsa.stattools import adfuller as ADF
import numpy as np
ADF(np.random.rand(100))

(-7.6403231041086483,
 1.9035306084034711e-11,
 1,
 98,
 {'1%': -3.4989097606014496,
  '10%': -2.5827604414827157,
  '5%': -2.891516256916761},
 23.882183569937467)