In [2]:
print(2+3)
print(2-3)
print(2*3)
print(10/2)
print(3**2)
print(10%4)

5
-1
6
5.0
9
2


In [3]:
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object_or_name, bases, dict)
 |  type(object) -> the object's type
 |  type(name, bases, dict) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(...)
 |      __dir__() -> list
 |      specialized __dir__ implementation for types
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(...)
 |      __instancecheck__() -> bool
 |      check if an object is an instance
 |  
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __prepare__(...)
 |      __prepare__() -> dict
 |      used to create the namespace for the class statement
 |  
 

In [4]:
print(type(5))
print(type(5.5))
print(type(5 + 3j))
print(type(True))
print(type(False))
print(type("2017 ithome ironman"))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bool'>
<class 'str'>


In [5]:
print(1.0 == True)
print(0 == False)
print(1.2 + True)
print(3 + True * 2)
print("2017 ithome ironman" + " rocks!")
print("2017 ithome ironman " + "rocks" + "!" * 3)

True
True
2.2
5
2017 ithome ironman rocks!
2017 ithome ironman rocks!!!


In [6]:
days = 30
print("In order to become an ironman, you have to publish an article a day for " + days + " days in a row.")

TypeError: Can't convert 'int' object to str implicitly

In [7]:
days = 30
days = days + 3
days

33

In [8]:
days = 30
days += 3
days

33

In [9]:
days = 30
days += 3
print(days)
days -= 3
print(days)
days *= 5
print(days)
days /= 5
print(days)
days %= 7
print(days)

33
30
150
30.0
2.0


In [10]:
days = 30
print("In order to become an ironman, you have tp publish an article a day for " + 
      str(days) + " days in a row.")

In order to become an ironman, you have tp publish an article a day for 30 days in a row.


In [11]:
my_bool = True
print(type(my_bool))
print(float(my_bool))
print(int(my_bool))
print(complex(my_bool))
print(type(str(my_bool)))

<class 'bool'>
1.0
1
(1+0j)
<class 'str'>


In [12]:
ironman_group_1 = "Modern Web"
ironman_group_2 = "DevOps"
ironman_group_3 = "Cloud"
ironman_group_4 = "Big Data"
ironman_group_5 = "Security"
ironman_group_6 = "自我挑戰組"

ironman_groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]

In [13]:
participated_group = "Big Data"
current_ttl_articles = 4
is_participating = True
my_status = [participated_group, current_ttl_articles, is_participating]
print(type(my_status[0]))
print(type(my_status[1]))
print(type(my_status[2]))

<class 'str'>
<class 'int'>
<class 'bool'>


In [14]:
ironman_groups_list = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security"]
ironman_groups_tuple = tuple(ironman_groups_list)

ironman_groups_list.insert(5, "自我挑戰組")
ironman_groups_tuple.insert(5, "自我挑戰組")

AttributeError: 'tuple' object has no attribute 'insert'

In [15]:
ironman_groups_list = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security"]
ironman_groups_tuple = tuple(ironman_groups_list)

ironman_groups_list.insert(5, "自我挑戰組")
print(ironman_groups_list)

['Modern Web', 'DevOps', 'Cloud', 'Big Data', 'Security', '自我挑戰組']


In [16]:
participated_group = "Big Data"
current_ttl_articles = 4
is_participating = True
my_status = {
    "group": participated_group,
    "ttl_articles": current_ttl_articles,
    "is_participating": is_participating
    }
print(my_status["group"])
print(my_status["ttl_articles"])
print(my_status["is_participating"])

Big Data
4
True


In [17]:
ironmen = [46, 8, 11, 11, 4, 56]
articles = ironmen * 30
print(articles)

[46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56]


In [18]:
ironmen = [46, 8, 11, 11, 4, 56]
article_multiplier = [30, 30, 30, 30, 30, 30]
articles = ironmen * article_multiplier
print(articles)

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
import numpy
ironmen = numpy.array([46, 8, 11, 11, 4, 56])
print(ironmen)
print(type(ironmen))
articles = ironmen * 30
print(articles)

[46  8 11 11  4 56]
<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


In [20]:
import numpy as np
my_np_array = np.array([1, True])
print(my_np_array.dtype)
my_np_array = np.array([1, True, "one"])
print(my_np_array.dtype)

int64
<U21


In [21]:
import numpy as np
my_2d_array = np.array([[1, True], 
                        [0, False]])
print(my_2d_array)
my_2d_array = np.array([[1, True], 
                        ["zero", False]])
print(my_2d_array)

[[1 1]
 [0 0]]
[['1' 'True']
 ['zero' 'False']]


In [22]:
import numpy as np
my_np_array = np.array([1, 2, 3, 4])
print(my_np_array ** 2)
my_2d_array = np.array([[1, 3], 
                        [2, 4]])
print(my_2d_array ** 2)

[ 1  4  9 16]
[[ 1  9]
 [ 4 16]]


In [23]:
import numpy as np
ironmen = np.array([46, 8, 11, 11, 4, 56])
print(ironmen[0])
print(ironmen > 10)
print(ironmen[ironmen > 10])

46
[ True False  True  True False  True]
[46 11 11 56]


In [24]:
import numpy as np
ironmen_2d_array = np.array([[46, 11, 4],
                             [8, 11, 56]])
print(ironmen_2d_array[0, 0])
print(ironmen_2d_array > 10)
print(ironmen_2d_array[ironmen_2d_array > 10])

46
[[ True  True False]
 [False  True  True]]
[46 11 11 56]


In [25]:
import numpy as np
ironmen_2d_array = np.array([[46, 11, 4],
                             [8, 11, 56]])
print(ironmen_2d_array.size)
print(ironmen_2d_array.shape)

6
(2, 3)


In [26]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"gorups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df)
print(type(ironmen_df))

       gorups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
4    Security        6
5       自我挑戰組       58
<class 'pandas.core.frame.DataFrame'>


In [27]:
import numpy as np
import pandas as pd
my_2d_array = np.array([[1, 3],
                        [2, 4]])
my_df = pd.DataFrame(my_2d_array, columns = ["col1", "col2"])
print(my_df)

   col1  col2
0     1     3
1     2     4


In [28]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.dtypes)

groups     object
ironmen     int64
dtype: object


In [29]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.iloc[0:1, 1])
print("---")
print(ironmen_df.iloc[0:1, :])
print("---")
print(ironmen_df.iloc[:, 1])
print("---")
print(ironmen_df["ironmen"])
print("---")
print(ironmen_df.ironmen)

0    46
Name: ironmen, dtype: int64
---
       groups  ironmen
0  Modern Web       46
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64


In [30]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

print(ironmen_df[ironmen_df.loc[:,"ironmen"] > 10])

       groups  ironmen
0  Modern Web       46
2       Cloud       12
3    Big Data       12
5       自我挑戰組       58


In [31]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"groups": groups, 
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.shape)
print("---")
print(ironmen_df.describe())
print("---")
print(ironmen_df.head(3))
print("---")
print(ironmen_df.tail(3))
print("---")
print(ironmen_df.columns)
print("---")
print(ironmen_df.index)

(6, 2)
---
         ironmen
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---
       groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
---
     groups  ironmen
3  Big Data       12
4  Security        6
5     自我挑戰組       58
---
Index(['groups', 'ironmen'], dtype='object')
---
Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')


In [32]:
import pandas as pd
groups_categorical = pd.Categorical(["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"])
print(groups_categorical)
print("---")
print(type(groups_categorical))

[Modern Web, DevOps, Cloud, Big Data, Security, 自我挑戰組]
Categories (6, object): [Big Data, Cloud, DevOps, Modern Web, Security, 自我挑戰組]
---
<class 'pandas.core.categorical.Categorical'>


In [33]:
import pandas as pd
temperature_list = ["cold", "warm", "hot"]
temperature_categorical = pd.Categorical(temperature_list, categories = ["cold", "warm", "hot"], ordered = True)
temperature = pd.Series(temperature_categorical)
print(temperature)

0    cold
1    warm
2     hot
dtype: category
Categories (3, object): [cold < warm < hot]


In [34]:
ironmen = [49, 8, 12, 12, 6, 61]
print(ironmen[0])
print(ironmen[1])
print(ironmen[2])
print(ironmen[3])
print(ironmen[4])
print(ironmen[5])

49
8
12
12
6
61


In [35]:
ironmen = [49, 8, 12, 12, 6, 61]
for ironman in ironmen:
    print(ironman)
print("---")
print(ironman)

print("\n")

for index in list(range(len(ironmen))):
    print(ironmen[index])
print("---")
print(index)

print(list(range(len(ironmen))))

49
8
12
12
6
61
---
61


49
8
12
12
6
61
---
5
[0, 1, 2, 3, 4, 5]


In [36]:
ironmen = [49, 8, 12, 12, 6, 61]
index = 0
while index < len(ironmen):
    print(ironmen[index])
    index += 1
print("---")
print(index)

49
8
12
12
6
61
---
6


In [37]:
my_seq = list(range(1, 11))
for index in my_seq:
    if (index % 2 == 0):
        print(index, "是偶數")
    else:
        print(index, "是奇數")

1 是奇數
2 是偶數
3 是奇數
4 是偶數
5 是奇數
6 是偶數
7 是奇數
8 是偶數
9 是奇數
10 是偶數


In [38]:
my_seq = list(range(1, 11))
for index in my_seq:
    if (index % 3 == 0):
        print(index, "可以被 3 整除")
    elif (index % 3 == 1):
        print(index, "除以 3 餘數是 1")
    else:
        print(index, "除以 3 餘數是 2")

1 除以 3 餘數是 1
2 除以 3 餘數是 2
3 可以被 3 整除
4 除以 3 餘數是 1
5 除以 3 餘數是 2
6 可以被 3 整除
7 除以 3 餘數是 1
8 除以 3 餘數是 2
9 可以被 3 整除
10 除以 3 餘數是 1


In [39]:
ironmen = [49, 8, 12, 12, 6, 61]
for ironman in ironmen:
    if(ironman < 10):
        break
    else:
        print(ironman)
print("---")
print(ironman)

print("\n")

for ironman in ironmen:
    if(ironman < 10):
        continue
    else:
        print(ironman)
        
print("---")
print(ironman)

49
---
8


49
12
12
61
---
61


In [40]:
sorted?
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customise the sort order, and the
    reverse flag can be set to request the result in descending order.



In [41]:
import math # 為了使用pi
def circle_calculate(radius, area = True):
    '依據輸入的半徑與area參數計算圓形的面積或周長'
    circle_area = math.pi * radius ** 2
    circle_circum = 2 * math.pi * radius
    if area == True:
        return circle_area
    else:
        return circle_circum
my_radius = 3
print(circle_calculate(my_radius))
print(circle_calculate(my_radius, area = False))

28.274333882308138
18.84955592153876


In [42]:
import random
def exchange_sort(input_list, reverse = False):
    ''' # 多行的docstrings
    依據輸入的 list 與 reverse 參數排序 list 中的數字後回傳。
    reverse 參數預設為 False 遞增排序，可以修改為 True 遞減排序。
    '''
    input_list_cloned = input_list
    if reverse == False:
        for i in range(0, len(input_list) - 1):
            for j in range(i + 1, len(input_list)):
                if input_list_cloned[i] > input_list_cloned[j]:
                    temp = input_list_cloned[i]
                    input_list_cloned[i] = input_list_cloned[j]
                    input_list_cloned[j] = temp
    else:
        for i in range(0, len(input_list) - 1):
            for j in range(i + 1, len(input_list)):
                if input_list_cloned[i] < input_list_cloned[j]:
                    temp = input_list_cloned[i]
                    input_list_cloned[i] = input_list_cloned[j]
                    input_list_cloned[j] = temp
    return input_list_cloned
my_vector = random.sample(range(0, 100), 10)
print(my_vector)
print(exchange_sort(my_vector))
print(exchange_sort(my_vector, reverse = True))

[59, 77, 48, 5, 13, 45, 37, 21, 16, 6]
[5, 6, 13, 16, 21, 37, 45, 48, 59, 77]
[77, 59, 48, 45, 37, 21, 16, 13, 6, 5]


In [43]:
def ironmen_stats(ironmen_list):
    max_ironmen = max(ironmen_list)
    min_ironmen = min(ironmen_list)
    ttl_groups = len(ironmen_list)
    ttl_ironmen = sum(ironmen_list)
    return max_ironmen, min_ironmen, ttl_groups, ttl_ironmen
    
ironmen = [50, 8, 16, 12, 6, 62]
max_ironmen, min_ironmen, ttl_groups, ttl_ironmen = ironmen_stats(ironmen)
print("\n", "最多：", max_ironmen, "\n", "最少：", min_ironmen, "\n", "總組數：", ttl_groups, "\n", "總鐵人數：", ttl_ironmen)


 最多： 62 
 最少： 6 
 總組數： 6 
 總鐵人數： 154


In [44]:
# 匿名函數lambda
ironmen = [50, 8, 16, 12, 6, 62]
ironmen_articles = list(map(lambda x : x * 30, ironmen))
print(ironmen_articles)

[1500, 240, 480, 360, 180, 1860]


In [45]:
def my_square(input_number):
    '計算平方數'
    ans = input_number ** 2
    return ans
print(my_square(3))
print(ans)

9


NameError: name 'ans' is not defined

In [ ]:
ans = 1
def my_square(input_number):
    '計算平方數'
    ans = input_number ** 2
    return ans
print(my_square(3))
print(ans)

In [46]:
def my_mean(input_list):
    '計算平均數'
    def my_sum(input_list):
        '計算總和'
        temp_sum = 0
        for i in input_list:
            temp_sum += i
        return temp_sum
    def my_length(input_list):
        '計算個數'
        temp_length = 0
        for i in input_list:
            temp_length += 1
        return temp_length
    return my_sum(input_list) / my_length(input_list)

my_list = [51, 8, 18, 13, 6, 64]
print(my_mean(my_list))

26.666666666666668


In [47]:
def my_square(input_number):
    '計算平方數且有錯誤處理的函數'
    try:
        ans = input_number ** 2
        return ans
    except:
        print("請輸入數值。")
print(my_square(3))
my_square('ironmen')

9
請輸入數值。


In [48]:
def ironmen_list(*args):
    '列出各組參賽帖人數'
    for ironman in args:
        print(ironman)

ironmen_list(51, 8, 18, 13, 6)
print("---")
ironmen_list(51, 8, 18, 13, 6)
print("---")
ironmen_list(51, 8, 18, 13, 6, 64)

51
8
18
13
6
---
51
8
18
13
6
---
51
8
18
13
6
64


In [49]:
def ironmen_list(**kwargs):
    '列出各組參賽鐵人數'
    for key in kwargs:
        print(key, "：", kwargs[key], "人")
ironmen_list(ModernWeb = 51, DevOps = 8, Cloud = 18, BigData = 13, Security = 6, 自我挑戰組 = 64)

DevOps ： 8 人
Cloud ： 18 人
Security ： 6 人
自我挑戰組 ： 64 人
ModernWeb ： 51 人
BigData ： 13 人


In [50]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [51, 8, 18, 14, 6, 64]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df.head(n = 3)

groups  ironmen
0  Modern Web       51
1      DevOps        8
2       Cloud       18

In [51]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [51, 8, 18, 14, 6, 64]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df.head(n = 3)

groups  ironmen
0  Modern Web       51
1      DevOps        8
2       Cloud       18

In [52]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [54, 8, 18, 14, 6, 65]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
print(ironmen_df.dtypes)
ironmen_df.head(n = 3)

groups     object
ironmen     int64
dtype: object


groups  ironmen
0  Modern Web       54
1      DevOps        8
2       Cloud       18

In [53]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別''' # Doc string
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants
print(Ironmen)

<class '__main__.Ironmen'>


In [54]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別'''
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants

# 根據 Ironmen 類別建立一個物件 modern_web
modern_web = Ironmen("Modern Web", 54)
print(modern_web)

In [55]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別'''
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants

# 根據 Ironmen 類別建立一個物件 modern_web
modern_web = Ironmen("Modern Web", 54)

# 印出 modern_web 的兩種屬性
print(modern_web.group)
print(modern_web.participants)

# 印出 modern_web 的類別 doc string
print(modern_web.__doc__)

Modern Web
54
這是一個叫做 Ironmen 的類別


In [56]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別'''
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants
        
# 根據 Ironmen 類別建立一個物件 modern_web
modern_web = Ironmen("Modern Web", 54)

dir(modern_web) # 看所有屬性

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'group',
 'participants']

In [58]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別''' # Doc string
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants
    def print_info(self):
        print(self.group, "組有", self.participants, "位鐵人參賽！")

# 根據 Ironmen 類別建立一個物件 modern_web
modern_web = Ironmen("Modern Web", 54)

# 根據 Ironmen 類別建立一個物件 dev_ops
dev_ops = Ironmen("DevOps", 8)

modern_web.print_info()
dev_ops.print_info()

Modern Web 組有 54 位鐵人參賽！
DevOps 組有 8 位鐵人參賽！


In [59]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別''' # Doc string
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants
    def print_info(self):
        print(self.group, "組有", self.participants, "位鐵人參賽！")

# Articles 類別繼承 Ironmen 類別
class Articles(Ironmen):
    '''
    這是一個叫做 Articles 的類別。
    Articles 繼承 Ironmen 類別，她新增了一個 print_articles()方法
    '''
    def print_articles(self):
        print(self.group, "組預計會有", self.participants * 30, "篇文章！")

# 根據 Articles 類別建立一個物件 modern_web
modern_web = Articles("Modern Web", 54)

# 使用 modern_web 的 print_articles() 方法
modern_web.print_articles()

# 檢查 modern_web 是否還擁有 print_info() 方法
modern_web.print_info()

Modern Web 組預計會有 1620 篇文章！
Modern Web 組有 54 位鐵人參賽！


In [60]:
class OnlyGroup:
    '''這是一個叫做 OnlyGroup 的類別''' # Doc string
    def __init__(self, group):
        self.group = group

# Ironmen 類別繼承 OnlyGroup 類別
class Ironmen(OnlyGroup):
    '''這是一個叫做 Ironmen 的類別''' # Doc string
    def __init__(self, group, participants):
        super().__init__(group)
        self.participants = participants

modern_web = Ironmen("Modern Web", 54)

print(modern_web.group)
print(modern_web.participants)

Modern Web
54


In [61]:
class Ironmen:
    '''這是一個叫做 Ironmen 的類別''' # Doc string
    def __init__(self, group, participants):
        self.group = group
        self.participants = participants
    def print_info(self):
        print(self.group, "組有", self.participants, "位鐵人參賽！")

class Articles(Ironmen):
    '''
    這是一個叫做 Articles 的類別。
    Articles 繼承 Ironmen 類別，她新增了一個 print_articles()方法
    '''
    def print_articles(self):
        print(self.group, "組預計會有", self.participants * 30, "篇文章！")
    def print_info(self):
        print(self.group, "組有", self.participants, "位鐵人參賽！p.s.我被改寫了！")

modern_web = Articles("Modern Web", 54)

modern_web.print_info()

Modern Web 組有 54 位鐵人參賽！p.s.我被改寫了！


In [63]:
my_float = 8.7
print(my_float.as_integer_ratio())
print(my_float.is_integer())
print(my_float.hex())
print(float.fromhex("0x1.1666666666666p+3"))

(2448832297382707, 281474976710656)
False
0x1.1666666666666p+3
8.7


In [64]:
my_int = 87
print(my_int.bit_length())
print(my_int.to_bytes(length = 2, byteorder = "big"))
print(int.from_bytes(b'\x00W', byteorder = "big"))
print("---")
print(my_int.to_bytes(length = 10, byteorder = "big"))
print(int.from_bytes(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00W', byteorder = "big"))

7
b'\x00W'
87
---
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00W'
87


In [65]:
my_complex = 8 + 7j
print(my_complex.real)
print(my_complex.imag)
print(my_complex.conjugate())

8.0
7.0
(8-7j)


In [74]:
my_str = "It's the 2017 ithelp ironman contest!!!"

print(my_str.startswith("It's"))
print(my_str.endswith("contest??"))
print(my_str.find("2017"))
print(my_str.count("!"))
print(my_str.strip("!"))
print(my_str.capitalize())
print(my_str.title())
print(my_str.upper())
print(my_str.lower())
print(my_str.swapcase())
print(my_str.replace("contest", "competition"))

True
False
9
3
It's the 2017 ithelp ironman contest
It's the 2017 ithelp ironman contest!!!
It'S The 2017 Ithelp Ironman Contest!!!
IT'S THE 2017 ITHELP IRONMAN CONTEST!!!
it's the 2017 ithelp ironman contest!!!
iT'S THE 2017 ITHELP IRONMAN CONTEST!!!
It's the 2017 ithelp ironman competition!!!


In [76]:
my_bool = True
print(my_bool.bit_length())
print(my_bool.to_bytes(length = 2, byteorder = "big"))
print(bool.from_bytes(b'\x00\x01', byteorder = "big"))
print("---")
print(my_bool.to_bytes(length = 10, byteorder = "big"))
print(bool.from_bytes(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01', byteorder = "big"))

1
b'\x00\x01'
True
---
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
True


In [80]:
ironmen = [56, 8, 18, 14, 6]

ironmen.append(66)
print(ironmen)
ironmen.pop()
print(ironmen)
ironmen.insert(5, 66)
ironmen.remove(66)
print(ironmen)
ironmen.index(56)
ironmen.append(66)
ironmen.append(66)
print(ironmen.count(66))
ironmen.pop()
ironmen.sort()
print(ironmen)
ironmen.reverse()
print(ironmen)

[56, 8, 18, 14, 6, 66]
[56, 8, 18, 14, 6]
[56, 8, 18, 14, 6]
2
[6, 8, 14, 18, 56, 66]
[66, 56, 18, 14, 8, 6]


In [81]:
my_tuple = (56, 8, 18, 14, 6, 6)
print(my_tuple.index(56))
print(my_tuple.count(6))

0
2


In [83]:
ironmen_dict = {"Modern Web": 56,
                "DevOps": 8,
                "Cloud": 18,
                "Big Data": 14,
                "Security": 6,
                "自我挑戰組": 66}
print(ironmen_dict.get("Modern Web"))
print(ironmen_dict.keys())
print(ironmen_dict.items())
print(ironmen_dict.values())
dir(ironmen_dict)

56
dict_keys(['Big Data', 'Modern Web', 'DevOps', 'Security', '自我挑戰組', 'Cloud'])
dict_items([('Big Data', 14), ('Modern Web', 56), ('DevOps', 8), ('Security', 6), ('自我挑戰組', 66), ('Cloud', 18)])
dict_values([14, 56, 8, 6, 66, 18])


['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [85]:
import numpy as np
ironmen = [56, 8, 19, 14, 6, 71]
ironmen_array = np.array(ironmen)

print(ironmen_array.ndim)
print(ironmen_array.shape)
print(ironmen_array.dtype)
print("\n")

ironmen_2d = [range(1, 7), [56, 8, 19, 14, 6, 71]]
ironmen_2d_array = np.array(ironmen_2d)
print(ironmen_2d_array.ndim)
print(ironmen_2d_array.shape)
print(ironmen_2d_array.dtype)
print(ironmen_2d_array)

1
(6,)
int64


2
(2, 6)
int64
[[ 1  2  3  4  5  6]
 [56  8 19 14  6 71]]


In [87]:
import numpy as np
print(np.zeros(6))
print("------")
print(np.zeros((2, 6)))
print("------")
print(np.empty((2, 6, 2)))
print("------")
print(np.arange(11))

[ 0.  0.  0.  0.  0.  0.]
------
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
------
[[[  0.00000000e+000   0.00000000e+000]
  [  2.12212532e-314   1.48219694e-323]
  [  0.00000000e+000   0.00000000e+000]
  [  0.00000000e+000   1.49034872e+255]
  [  2.12378304e-314   2.27840274e-314]
  [  5.51497249e-144   0.00000000e+000]]

 [[  0.00000000e+000   1.07262055e-062]
  [  0.00000000e+000   0.00000000e+000]
  [  5.44021989e-062   0.00000000e+000]
  [  0.00000000e+000  -3.44757662e+139]
  [  0.00000000e+000   0.00000000e+000]
  [ -7.14671141e-204   0.00000000e+000]]]
------
[ 0  1  2  3  4  5  6  7  8  9 10]


In [88]:
import numpy as np
ironmen = ["56", "8", "19", "14", "6", "71"]
ironmen_str_array = np.array(ironmen)
print(ironmen_str_array.dtype)
print("---")

ironmen_int_array = ironmen_str_array.astype(np.int64)
print(ironmen_int_array.dtype)

<U2
---
int64


In [89]:
import numpy as np

my_array = np.arange(10)
print(my_array[0])
print(my_array[0:5])
print("---")

my_2d_array = np.array([np.arange(0, 5), np.arange(5, 10)])
print(my_2d_array)
print("---")
print(my_2d_array[1, :])
print(my_2d_array[:, 1])
print(my_2d_array[1, 1])

0
[0 1 2 3 4]
---
[[0 1 2 3 4]
 [5 6 7 8 9]]
---
[5 6 7 8 9]
[1 6]
6


In [90]:
import numpy as np
ironmen = [56, 8, 19, 14, 6, 71]
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_array = np.array(ironmen)
groups_array = np.array(groups)

print(ironmen_array >= 10)
print(groups_array[ironmen_array >= 10])

print(groups_array != "自我挑戰組")
print(ironmen_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


In [92]:
import numpy as np

my_1d_array = np.arange(10)
my_2d_array = my_1d_array.reshape((2, 5))
print(my_2d_array)
print("---")
print(my_2d_array.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
---
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [93]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, np.nan])
np.where(np.isnan(ironmen_array), 71, ironmen_array)

array([ 56.,   8.,  19.,  14.,   6.,  71.])

In [94]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, 71])
print(ironmen_array)
ironmen_array.sort()
print(ironmen_array)

[56  8 19 14  6 71]
[ 6  8 14 19 56 71]


In [96]:
import numpy as np

normal_samples = np.random.normal(size = 10)
uniform_samples = np.random.uniform(size = 10)

print(normal_samples)
print("---")
print(uniform_samples)

[ 0.65997603 -0.28419671 -0.47752129 -1.59717009 -0.76856976 -0.76327634
  0.0927956  -1.51265569  1.60932869  1.32844077]
---
[ 0.14865155  0.85820735  0.76652138  0.24338557  0.39505941  0.44011054
  0.86212266  0.45681428  0.62587681  0.27979068]


In [2]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       59
1      DevOps        9
2       Cloud       19
3    Big Data       14
4    Security        6
5       自我挑戰組       77

In [3]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

print(ironmen_df.ndim)
print("---")
print(ironmen_df.shape)
print("---")
print(ironmen_df.dtypes)

2
---
(6, 2)
---
groups     object
ironmen     int64
dtype: object


In [5]:
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

ironmen_df_no_mw = ironmen_df.drop(0, axis = 0)
print(ironmen_df_no_mw)
print("---")

ironmen_df_no_groups = ironmen_df.drop("groups", axis = 1)
print(ironmen_df_no_groups)

     groups  ironmen
1    DevOps        9
2     Cloud       19
3  Big Data       14
4  Security        6
5     自我挑戰組       77
---
   ironmen
0       59
1        9
2       19
3       14
4        6
5       77


In [7]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_dict = {"groups": groups, 
                "ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

print(ironmen_df.ix[:, "groups"])
print("---")

print(ironmen_df.ix[0])
print("---")

print(ironmen_df.ix[0, "groups"])

0    Modern Web
1        DevOps
2         Cloud
3      Big Data
4      Security
5         自我挑戰組
Name: groups, dtype: object
---
groups     Modern Web
ironmen            59
Name: 0, dtype: object
---
Modern Web


In [8]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

filter = ironmen_df["ironmen"] > 10
ironmen_df[filter]

groups  ironmen
0  Modern Web       59
2       Cloud       19
3    Big Data       14
5       自我挑戰組       77

In [10]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
print(ironmen_df)
print(ironmen_df.sort_index())

            ironmen
Modern Web       59
DevOps            9
Cloud            19
Big Data         14
Security          6
自我挑戰組            77
            ironmen
Big Data         14
Cloud            19
DevOps            9
Modern Web       59
Security          6
自我挑戰組            77


In [11]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [59, 9, 19, 14, 6, 77]

ironmen_df = pd.DataFrame(ironmen, columns = ["ironmen"], index = groups)
ironmen_df.sort_values(by = "ironmen")

ironmen
Security          6
DevOps            9
Big Data         14
Cloud            19
Modern Web       59
自我挑戰組            77